### ISSUE TITLE
closing last tab using toolbar should take to firefox homepage

### ISSUE THREAD

**Issue by sheikh-azharuddin** [KristhianX/essential-buttons-toolbar#20]
On closing the last tab using the close button, instead of going to firefox homepage it is going to tabliss page, is it possible to change to go to firefox homepage instead? Any option or suggestions please

**Comment by KristhianX** [comment]
Hi! Thanks for using the add-on and giving feedback.

Unfortunately, the functionality you requested is not possible. The Firefox homepage on Android is not a tab and does not have a URL. It is part of the browser UI and cannot be accessed by add-ons.

I am working on a Firefox homepage replacement for the next update. See issue #6.

**Comment by Siva981** [comment]
Hi,

I got a version of this request accomplished, by a workaround using the "Homepage URL" option in EBTB's Settings.

Instead of using a real URL, or even "about:blank", I have just entered "about:".

The end result is kind of ugly, but gets the job done for me on my Samsung Galaxy M01 (Android 12).

1) It closes even the last tab.

2) It does not open any new tab.

3) But .... the last tab will appear as though it has not closed. Everything below Firefox's address bar will be displayed as it was (even EBTB) before. Meaning, it will be displayed how it was before we tapped EBTB's "Close Tab" button on the last remaining tab. But nothing on the page will be clickable anymore. Because the tab has actually gotten closed.

4) Now, all we got to do is:

a) Select Firefox's Address Bar

Or

b) Tap the Home button of Firefox 

Or

C) Access any of Firefox's Settings (Bookmarks or History will do).

5) When we do any one of the things mentioned on Step 4 above, whatever remained on the page after closing the last remaining tab (as explained on Step 3 above) using EBTB's Close Tab button dissappears, and Firefox's Home page is revealed.

Please refer the Screen Recording below for clarity.

It may not exactly be the perfect solution, but it works for me, lol.


https://github.com/user-attachments/assets/ac15cf8a-de86-4ad2-9eb7-accb034282b8
