### ISSUE TITLE
The toolbar's height is too big and isn't the same as in the settings

### ISSUE THREAD

**Issue by MilaMurry** [KristhianX/essential-buttons-toolbar#23]
Hello there, it's me again 😁.

The toolbar is too big for this [website](https://www.javascripttutorial.net/javascript-dom/javascript-style/). The fix would be adding a
```css
min-height: `${height}px`
```

Another thing is that the height in the iframe is not the same as what I set in the settings. The height in settings is 42px, but in the iframe it is 41px as seen in eruda.

**Comment by KristhianX** [comment]
Hi! How are you doing?

Nice catch, thanks for reporting it. I'll investigate it to include the fix in the next update.

**Comment by MilaMurry** [comment]
I'm fine, thank you. I hope you are too.
No biggie, no rush 😉.

**Comment by KristhianX** [comment]
Hi @MilaMurry! I hope you’re doing great. I haven’t been able to work on the add-on in the past few months. I had to move to another city and didn’t have access to my computer, but I do now and am happy to keep improving the add-on. I’m focusing on fixing bugs first and then gradually working on new features.

The toolbar size issue on that website was resolved some time ago. Regarding the inconsistency between the height set in the settings and the actual toolbar height: on most sites, the add-on will display at the correct height. However, for some sites—especially those in Desktop mode—the add-on needs to calculate the height based on `window.visualViewport.scale`. The result isn’t always a whole number, so I use `Math.floor()` to round it down.

I tested several sites and couldn’t find one where the actual size differs from the set height. If you remember the specific site with the inconsistency and would like to share it, I could try rounding the number up instead of down. If the inconsistency no longer occurs, or if the difference is minor, we could consider this issue resolved.
