### ISSUE TITLE
Always show toolbar is disable when zoom on a page

### ISSUE THREAD

**Issue by magi44ken** [KristhianX/essential-buttons-toolbar#25]
Bug: If you set the toolbar always shown, if you zoom in the page, it gets disable and switch to auto hide toolbar. Is there a possible fix?

**Comment by KristhianX** [comment]
Hi, thank you for using the add-on and providing feedback.

The toolbar zooms along with the page, going out of the viewport. This is its normal behavior.
The toolbar CSS display property is set to 'fixed' and is positioned either 0 pixels from the top or bottom, depending on the settings, to make it feel part of the UI.

While it is possible to adjust the toolbar's size dynamically on zoom changes, this approach leads to choppy results, causing the toolbar to jump and leaving gaps at the edges. Some users may find this behavior annoying when zooming and panning within the page. Therefore, it's preferable to keep the toolbar fixed in place and zoom out the page to make it visible again.
