### ISSUE TITLE
[Feature request] Tab menu

### ISSUE THREAD

**Issue by MilaMurry** [KristhianX/essential-buttons-toolbar#7]
A tab menu would be fantastic if you have multiple tabs opened, easier to switch between them and remove them as well. And a long press to reorder them.
I prefer it to be able to scroll horizontally but some may prefer it vertically.
If the menu's height can be specified to your liking, that would be better.

**Comment by KristhianX** [comment]
Since `tabs.query({})` does not return the correct number of tabs, information from those tabs (title, URL, favicon) cannot be retrieved. This will require adding listeners for tab events (create, remove, update, etc.) to keep a list of tabs to work with.

**Comment by mglh** [comment]
I second this feature request.

**Comment by KristhianX** [comment]
Update about this:

I finally took the time to investigate this better. The workaround I had in mind when I made my previous comment is not possible. As I mentioned there, `tabs.query` will only output the list of loaded tabs.

I thought that, if we could store the `id` of the tab when it was opened, we could operate on it even if the tab became idle/unloaded. Not only does the tab unload, it is effectively closed.
When you select an unloaded tab, the browser assigns a new `id` to it.

For that reason, having a list of ids as a workaround is not useful. I tried to send commands to an unloaded tab, using the id it had when it was loaded, and the browser complains about the id not existing.

I was really excited to make this work, since I want other functions of the add-on to benefit from having the full list of opened tabs (for example, to make the 'Close all tabs' and 'Close other tabs' buttons function properly). But given these limitations, I don't think making a tab menu/bar is worth it, since it will be incomplete.

There is an [add-on](https://addons.mozilla.org/en-US/firefox/addon/tablet-ui-for-firefox/) that inserts a tab bar into pages, and the developer made a great job. You can give it a try to see the behavior that is currently possible.

Also, the Firefox developers have been working on incorporating a tab bar to Android Firefox, especially for tablet users. It was available on Nightly some weeks ago, it may be available on Beta already or, hopefully, in the near future.

I will close this now as not possible, and I will leave a comment on [this](https://discourse.mozilla.org/t/top-apis-missing-on-firefox-for-android/) thread to request (as other developers have done) that the tabs API gets better support.
